
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

format: ## Run pre-commit hooks
	pre-commit run -a

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

.PHONY: docs
# always execute the docs commands, even if there are no changes in ./docs
# make html will still consider previously generated documentation
docs: ## Generate documentation
	cd docs && $(MAKE) html

docs-clean: ## Build docs from scratch (also remove autogenerated reference files)
	cd docs && rm -rf build/ source/reference && $(MAKE) html
