# path to data directory
data_dir: ${oc.env:DFT_DATA}

# path to logging directory
log_dir: ${oc.env:DFT_MODELS}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/config.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
